# Mosquitto-config voor de GPS Tracker
# Start met:  mosquitto -c mosquitto.conf -v
#
# Twee listeners:
#   1883  -> normale MQTT (TCP), gebruikt door de Python-publisher
#   9001  -> MQTT-over-WebSocket, gebruikt door de website (browser)

listener 1883
protocol mqtt

listener 9001
protocol websockets

# Lokale ontwikkeling: anonieme toegang toestaan.
# Zet dit op 'false' + voeg een password_file toe voor productie.
allow_anonymous true

# (optioneel) bewaar retained messages over herstarts heen
persistence true
persistence_location ./data/
